/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiWikiIdIndexRouteImport } from './routes/wiki/$wikiId/index'
import { Route as WikiWikiIdSplatRouteImport } from './routes/wiki/$wikiId.$'

const WikiWikiIdIndexRoute = WikiWikiIdIndexRouteImport.update({
  id: '/wiki/$wikiId/',
  path: '/wiki/$wikiId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiWikiIdSplatRoute = WikiWikiIdSplatRouteImport.update({
  id: '/wiki/$wikiId/$',
  path: '/wiki/$wikiId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/wiki/$wikiId/$': typeof WikiWikiIdSplatRoute
  '/wiki/$wikiId/': typeof WikiWikiIdIndexRoute
}
export interface FileRoutesByTo {
  '/wiki/$wikiId/$': typeof WikiWikiIdSplatRoute
  '/wiki/$wikiId': typeof WikiWikiIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/wiki/$wikiId/$': typeof WikiWikiIdSplatRoute
  '/wiki/$wikiId/': typeof WikiWikiIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/wiki/$wikiId/$' | '/wiki/$wikiId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/wiki/$wikiId/$' | '/wiki/$wikiId'
  id: '__root__' | '/wiki/$wikiId/$' | '/wiki/$wikiId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WikiWikiIdSplatRoute: typeof WikiWikiIdSplatRoute
  WikiWikiIdIndexRoute: typeof WikiWikiIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki/$wikiId/': {
      id: '/wiki/$wikiId/'
      path: '/wiki/$wikiId'
      fullPath: '/wiki/$wikiId/'
      preLoaderRoute: typeof WikiWikiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$wikiId/$': {
      id: '/wiki/$wikiId/$'
      path: '/wiki/$wikiId/$'
      fullPath: '/wiki/$wikiId/$'
      preLoaderRoute: typeof WikiWikiIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WikiWikiIdSplatRoute: WikiWikiIdSplatRoute,
  WikiWikiIdIndexRoute: WikiWikiIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
