version: 2

project_name: lumina

builds:
  - id: lumina
    main: .
    binary: lumina
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets:
      # 主流部署与开发平台。
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64

archives:
  - id: release-binaries
    ids:
      - lumina
    formats:
      - binary
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{- if eq .Os "windows" }}.exe{{- end }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  make_latest: true
  mode: replace
  name_template: "{{ .Tag }}"
  preflight:
    fail_on_error: true

changelog:
  disable: true
