/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InteractRouteImport } from './routes/interact'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as InteractIndexRouteImport } from './routes/interact/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ConsoleSettingsRouteImport } from './routes/console/settings'
import { Route as ConsoleQaRouteImport } from './routes/console/qa'
import { Route as ConsoleProjectRouteImport } from './routes/console/project'
import { Route as ConsoleDashboardRouteImport } from './routes/console/dashboard'
import { Route as ConsoleApikeyRouteImport } from './routes/console/apikey'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthNewRouteImport } from './routes/auth/new'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PublicStartRouteImport } from './routes/_public/start'
import { Route as ConsoleQaSessionIdRouteImport } from './routes/console/qa/$sessionId'

const InteractRoute = InteractRouteImport.update({
  id: '/interact',
  path: '/interact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractIndexRoute = InteractIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InteractRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleQaRoute = ConsoleQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectRoute = ConsoleProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleApikeyRoute = ConsoleApikeyRouteImport.update({
  id: '/apikey',
  path: '/apikey',
  getParentRoute: () => ConsoleRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewRoute = AuthNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PublicStartRoute = PublicStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => PublicRoute,
} as any)
const ConsoleQaSessionIdRoute = ConsoleQaSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ConsoleQaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/interact': typeof InteractRouteWithChildren
  '/start': typeof PublicStartRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new': typeof AuthNewRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/console/apikey': typeof ConsoleApikeyRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/project': typeof ConsoleProjectRoute
  '/console/qa': typeof ConsoleQaRouteWithChildren
  '/console/settings': typeof ConsoleSettingsRoute
  '/console/': typeof ConsoleIndexRoute
  '/interact/': typeof InteractIndexRoute
  '/console/qa/$sessionId': typeof ConsoleQaSessionIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/start': typeof PublicStartRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new': typeof AuthNewRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/console/apikey': typeof ConsoleApikeyRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/project': typeof ConsoleProjectRoute
  '/console/qa': typeof ConsoleQaRouteWithChildren
  '/console/settings': typeof ConsoleSettingsRoute
  '/': typeof PublicIndexRoute
  '/console': typeof ConsoleIndexRoute
  '/interact': typeof InteractIndexRoute
  '/console/qa/$sessionId': typeof ConsoleQaSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/interact': typeof InteractRouteWithChildren
  '/_public/start': typeof PublicStartRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new': typeof AuthNewRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/console/apikey': typeof ConsoleApikeyRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/project': typeof ConsoleProjectRoute
  '/console/qa': typeof ConsoleQaRouteWithChildren
  '/console/settings': typeof ConsoleSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/interact/': typeof InteractIndexRoute
  '/console/qa/$sessionId': typeof ConsoleQaSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/interact'
    | '/start'
    | '/auth/login'
    | '/auth/new'
    | '/auth/reset-password'
    | '/console/apikey'
    | '/console/dashboard'
    | '/console/project'
    | '/console/qa'
    | '/console/settings'
    | '/console/'
    | '/interact/'
    | '/console/qa/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/start'
    | '/auth/login'
    | '/auth/new'
    | '/auth/reset-password'
    | '/console/apikey'
    | '/console/dashboard'
    | '/console/project'
    | '/console/qa'
    | '/console/settings'
    | '/'
    | '/console'
    | '/interact'
    | '/console/qa/$sessionId'
  id:
    | '__root__'
    | '/_public'
    | '/auth'
    | '/console'
    | '/interact'
    | '/_public/start'
    | '/auth/login'
    | '/auth/new'
    | '/auth/reset-password'
    | '/console/apikey'
    | '/console/dashboard'
    | '/console/project'
    | '/console/qa'
    | '/console/settings'
    | '/_public/'
    | '/console/'
    | '/interact/'
    | '/console/qa/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConsoleRoute: typeof ConsoleRouteWithChildren
  InteractRoute: typeof InteractRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/interact': {
      id: '/interact'
      path: '/interact'
      fullPath: '/interact'
      preLoaderRoute: typeof InteractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interact/': {
      id: '/interact/'
      path: '/'
      fullPath: '/interact/'
      preLoaderRoute: typeof InteractIndexRouteImport
      parentRoute: typeof InteractRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/qa': {
      id: '/console/qa'
      path: '/qa'
      fullPath: '/console/qa'
      preLoaderRoute: typeof ConsoleQaRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/project': {
      id: '/console/project'
      path: '/project'
      fullPath: '/console/project'
      preLoaderRoute: typeof ConsoleProjectRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/dashboard': {
      id: '/console/dashboard'
      path: '/dashboard'
      fullPath: '/console/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/apikey': {
      id: '/console/apikey'
      path: '/apikey'
      fullPath: '/console/apikey'
      preLoaderRoute: typeof ConsoleApikeyRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/new': {
      id: '/auth/new'
      path: '/new'
      fullPath: '/auth/new'
      preLoaderRoute: typeof AuthNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/start': {
      id: '/_public/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof PublicStartRouteImport
      parentRoute: typeof PublicRoute
    }
    '/console/qa/$sessionId': {
      id: '/console/qa/$sessionId'
      path: '/$sessionId'
      fullPath: '/console/qa/$sessionId'
      preLoaderRoute: typeof ConsoleQaSessionIdRouteImport
      parentRoute: typeof ConsoleQaRoute
    }
  }
}

interface PublicRouteChildren {
  PublicStartRoute: typeof PublicStartRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicStartRoute: PublicStartRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNewRoute: typeof AuthNewRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthNewRoute: AuthNewRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ConsoleQaRouteChildren {
  ConsoleQaSessionIdRoute: typeof ConsoleQaSessionIdRoute
}

const ConsoleQaRouteChildren: ConsoleQaRouteChildren = {
  ConsoleQaSessionIdRoute: ConsoleQaSessionIdRoute,
}

const ConsoleQaRouteWithChildren = ConsoleQaRoute._addFileChildren(
  ConsoleQaRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleApikeyRoute: typeof ConsoleApikeyRoute
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleProjectRoute: typeof ConsoleProjectRoute
  ConsoleQaRoute: typeof ConsoleQaRouteWithChildren
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleApikeyRoute: ConsoleApikeyRoute,
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleProjectRoute: ConsoleProjectRoute,
  ConsoleQaRoute: ConsoleQaRouteWithChildren,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface InteractRouteChildren {
  InteractIndexRoute: typeof InteractIndexRoute
}

const InteractRouteChildren: InteractRouteChildren = {
  InteractIndexRoute: InteractIndexRoute,
}

const InteractRouteWithChildren = InteractRoute._addFileChildren(
  InteractRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConsoleRoute: ConsoleRouteWithChildren,
  InteractRoute: InteractRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
