// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/apikey": {
            "get": {
                "description": "按 page/size 分页查询 API 密钥列表，密钥以脱敏形式展示",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API密钥接口"
                ],
                "summary": "[管理] 分页获取API密钥列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量（最大200）",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功，密钥脱敏展示",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/xModels.PageResponse-array_apikey_ApikeyItem"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "提交名称与可选描述/过期时间创建 API 密钥，返回完整密钥（仅此一次）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API密钥接口"
                ],
                "summary": "[管理] 创建API密钥",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apikey.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功，返回完整密钥（仅此一次）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apikey.CreateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/apikey/{id}": {
            "get": {
                "description": "根据密钥 ID 查询单个 API 密钥详情，密钥以脱敏形式展示",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API密钥接口"
                ],
                "summary": "[管理] 获取API密钥详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API密钥ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功，密钥脱敏展示",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apikey.DetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "密钥不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定 ID 的 API 密钥信息（名称、描述、过期时间、启用状态，字段可选）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API密钥接口"
                ],
                "summary": "[管理] 更新API密钥",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API密钥ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apikey.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "密钥不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据密钥 ID 删除指定的 API 密钥，删除后不可恢复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API密钥接口"
                ],
                "summary": "[管理] 删除API密钥",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API密钥ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "密钥不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/apikey/{id}/reset": {
            "post": {
                "description": "根据密钥 ID 重置密钥，生成新密钥并返回完整密钥（仅此一次）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API密钥接口"
                ],
                "summary": "[管理] 重置API密钥",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API密钥ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "重置成功，返回新完整密钥（仅此一次）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apikey.ResetResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "密钥不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/initialize": {
            "post": {
                "description": "首次部署时提交用户名、邮箱、密码，初始化系统管理员账户；已初始化时拒绝",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证接口"
                ],
                "summary": "[超管] 系统初始化",
                "parameters": [
                    {
                        "description": "初始化请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.InitializeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "初始化成功",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "409": {
                        "description": "系统已初始化",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "校验账号（用户名或邮箱）与密码，签发访问令牌与刷新令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证接口"
                ],
                "summary": "[管理] 用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "账号或密码错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "根据刷新令牌撤销登录会话，需携带有效访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证接口"
                ],
                "summary": "[管理] 用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "登出请求（传入 refresh_token）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "使用刷新令牌换取新的访问令牌与刷新令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证接口"
                ],
                "summary": "[管理] 刷新令牌",
                "parameters": [
                    {
                        "description": "刷新请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功，返回新令牌",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "刷新令牌无效",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/status": {
            "get": {
                "description": "查询系统是否已完成初始化，前端据此决定展示初始化页或登录页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证接口"
                ],
                "summary": "系统初始化状态",
                "responses": {
                    "200": {
                        "description": "查询成功，返回初始化状态",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.StatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/health/ping": {
            "get": {
                "description": "探测服务存活状态，返回应用版本、数据库与 Redis 就绪情况",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康检查接口"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "服务正常",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/health.PingResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "依赖服务不可用",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/project": {
            "get": {
                "description": "按 page/size 分页查询项目列表，返回项目信息与总数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目接口"
                ],
                "summary": "[管理] 获取项目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/project.ProjectListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "提交项目名称、别名、匹配路径与描述创建项目，名称需唯一",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目接口"
                ],
                "summary": "[管理] 创建项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建项目请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/project.ProjectResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "409": {
                        "description": "项目名称已存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/project/{id}": {
            "get": {
                "description": "根据项目 ID 查询单个项目详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目接口"
                ],
                "summary": "[管理] 获取项目详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/project.ProjectResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "项目不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定 ID 的项目信息，名称需保持唯一",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目接口"
                ],
                "summary": "[管理] 更新项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新项目请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.UpdateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/project.ProjectResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "项目不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "409": {
                        "description": "项目名称已存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据项目 ID 删除指定项目，删除后不可恢复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目接口"
                ],
                "summary": "[管理] 删除项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "项目不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/qa/config": {
            "get": {
                "description": "查询当前 Q\u0026A 模块运行配置（会话TTL、运行时域名、轮询参数、重试次数）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Q\u0026A接口"
                ],
                "summary": "[管理] 获取Q\u0026A配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/qa.QaConfigResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新 Q\u0026A 模块运行配置，所有字段可选（nil 表示不更新）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Q\u0026A接口"
                ],
                "summary": "[管理] 更新Q\u0026A配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "配置信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/qa.UpdateQaConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/qa.QaConfigResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/qa/sessions": {
            "get": {
                "description": "按 page/size 分页查询会话列表，支持按状态与类型过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Q\u0026A接口"
                ],
                "summary": "[管理] 分页获取QA会话列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态过滤(active/expired/deleted)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "类型过滤(temporary/permanent)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/qa.SessionListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "关联项目 ID 创建 Q\u0026A 会话，支持指定标题、Agent 名称与会话类型，返回会话详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Q\u0026A接口"
                ],
                "summary": "[管理] 创建QA会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/qa.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/qa.SessionDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/qa/sessions/{id}": {
            "get": {
                "description": "根据会话 ID 查询会话详情，含完整问题列表（含回答与补充内容）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Q\u0026A接口"
                ],
                "summary": "[管理] 获取QA会话详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/qa.SessionDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据会话 ID 删除指定会话及其关联问题，删除后不可恢复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Q\u0026A接口"
                ],
                "summary": "[管理] 删除QA会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/qa/sessions/{id}/questions/{qid}": {
            "get": {
                "description": "根据会话 ID 与问题 ID 查询问题详情，含回答内容与关联补充内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Q\u0026A接口"
                ],
                "summary": "[管理] 获取问题详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "问题ID",
                        "name": "qid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/qa.QuestionDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    },
                    "404": {
                        "description": "问题不存在",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/current": {
            "get": {
                "description": "根据访问令牌获取当前登录用户信息（用户名、邮箱）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "[管理] 获取当前用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Access Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功，返回用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.UserInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/common.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apikey.ApikeyItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间",
                    "type": "string"
                },
                "id": {
                    "description": "API Key ID",
                    "type": "string"
                },
                "is_active": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "key": {
                    "description": "脱敏密钥",
                    "type": "string"
                },
                "key_prefix": {
                    "description": "密钥前缀",
                    "type": "string"
                },
                "last_used_at": {
                    "description": "最后使用时间",
                    "type": "string"
                },
                "name": {
                    "description": "API Key名称",
                    "type": "string"
                }
            }
        },
        "apikey.CreateRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间（NULL=永不过期）",
                    "type": "string"
                },
                "name": {
                    "description": "API Key名称",
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                }
            }
        },
        "apikey.CreateResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间（手动映射，BaseEntity.CreatedAt 的 json:\"-\"）",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间",
                    "type": "string"
                },
                "id": {
                    "description": "API Key ID",
                    "type": "string"
                },
                "is_active": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "key": {
                    "description": "完整密钥（仅此一次）",
                    "type": "string"
                },
                "key_prefix": {
                    "description": "密钥前缀",
                    "type": "string"
                },
                "name": {
                    "description": "API Key名称",
                    "type": "string"
                }
            }
        },
        "apikey.DetailResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间",
                    "type": "string"
                },
                "id": {
                    "description": "API Key ID",
                    "type": "string"
                },
                "is_active": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "key": {
                    "description": "脱敏密钥（前8+...+后8）",
                    "type": "string"
                },
                "key_prefix": {
                    "description": "密钥前缀",
                    "type": "string"
                },
                "last_used_at": {
                    "description": "最后使用时间",
                    "type": "string"
                },
                "name": {
                    "description": "API Key名称",
                    "type": "string"
                }
            }
        },
        "apikey.ResetResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间",
                    "type": "string"
                },
                "id": {
                    "description": "API Key ID",
                    "type": "string"
                },
                "is_active": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "key": {
                    "description": "新完整密钥（仅此一次）",
                    "type": "string"
                },
                "key_prefix": {
                    "description": "密钥前缀",
                    "type": "string"
                },
                "name": {
                    "description": "API Key名称",
                    "type": "string"
                }
            }
        },
        "apikey.UpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "描述（指针区分零值和未传）",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间",
                    "type": "string"
                },
                "is_active": {
                    "description": "是否启用（指针区分零值和未传）",
                    "type": "boolean"
                },
                "name": {
                    "description": "API Key名称",
                    "type": "string"
                }
            }
        },
        "auth.InitializeRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "password": {
                    "description": "登录密码",
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 6
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "description": "账号（用户名或邮箱）",
                    "type": "string"
                },
                "password": {
                    "description": "登录密码",
                    "type": "string"
                }
            }
        },
        "auth.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string"
                }
            }
        },
        "auth.StatusResponse": {
            "type": "object",
            "properties": {
                "is_initial": {
                    "description": "系统是否为初始状态（true=未初始化）",
                    "type": "boolean"
                }
            }
        },
        "auth.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "访问令牌",
                    "type": "string"
                },
                "expires_in": {
                    "description": "过期时间（秒）",
                    "type": "integer"
                },
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string"
                }
            }
        },
        "common.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "context": {
                    "type": "string"
                },
                "data": {},
                "error_message": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                },
                "overhead": {
                    "type": "integer"
                }
            }
        },
        "health.PingResponse": {
            "type": "object",
            "properties": {
                "app": {
                    "type": "string"
                },
                "database_ready": {
                    "type": "boolean"
                },
                "redis_ready": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "project.CreateProjectRequest": {
            "type": "object",
            "required": [
                "match_path",
                "name"
            ],
            "properties": {
                "alias_name": {
                    "description": "项目别名",
                    "type": "string"
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "match_path": {
                    "description": "项目路径匹配列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                }
            }
        },
        "project.ProjectListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "项目列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project.ProjectResponse"
                    }
                },
                "total": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "project.ProjectResponse": {
            "type": "object",
            "properties": {
                "alias_name": {
                    "description": "项目别名",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "id": {
                    "description": "项目ID",
                    "type": "string"
                },
                "match_path": {
                    "description": "项目路径匹配列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "project.UpdateProjectRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "alias_name": {
                    "description": "项目别名",
                    "type": "string"
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "match_path": {
                    "description": "项目路径匹配列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                }
            }
        },
        "qa.CreateSessionRequest": {
            "type": "object",
            "required": [
                "project_id"
            ],
            "properties": {
                "agent": {
                    "description": "Agent名称",
                    "type": "string"
                },
                "project_id": {
                    "description": "关联项目ID",
                    "type": "string"
                },
                "title": {
                    "description": "会话标题",
                    "type": "string"
                },
                "type": {
                    "description": "temporary/permanent",
                    "type": "string"
                }
            }
        },
        "qa.QaConfigResponse": {
            "type": "object",
            "properties": {
                "max_retries": {
                    "description": "qa_get_answer 最大重试次数",
                    "type": "integer"
                },
                "poll_slice": {
                    "description": "qa_get_answer 单次阻塞上限（秒）",
                    "type": "integer"
                },
                "runtime_domain": {
                    "description": "运行时域名",
                    "type": "string"
                },
                "session_ttl": {
                    "description": "Session TTL（秒）",
                    "type": "integer"
                }
            }
        },
        "qa.QuestionDetailResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "回答数据"
                },
                "answered_at": {
                    "description": "回答时间",
                    "type": "string"
                },
                "batch": {
                    "description": "分批信息"
                },
                "config": {
                    "description": "题型特有配置"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "group_label": {
                    "description": "分组标签",
                    "type": "string"
                },
                "id": {
                    "description": "问题ID",
                    "type": "string"
                },
                "options": {
                    "description": "选项配置"
                },
                "session_id": {
                    "description": "所属Session",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "supplements": {
                    "description": "关联补充内容",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/qa.SupplementResponse"
                    }
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "type": {
                    "description": "题型",
                    "type": "string"
                }
            }
        },
        "qa.QuestionSummaryResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "回答数据"
                },
                "answered_at": {
                    "description": "回答时间",
                    "type": "string"
                },
                "batch": {
                    "description": "分批信息"
                },
                "config": {
                    "description": "题型特有配置"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "group_label": {
                    "description": "分组标签",
                    "type": "string"
                },
                "id": {
                    "description": "问题ID",
                    "type": "string"
                },
                "media": {
                    "description": "多媒体数据"
                },
                "options": {
                    "description": "选项配置"
                },
                "status": {
                    "description": "pending/answered/skipped",
                    "type": "string"
                },
                "supplement": {
                    "description": "是否携带补充内容",
                    "type": "boolean"
                },
                "supplements": {
                    "description": "关联补充内容",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/qa.SupplementResponse"
                    }
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "type": {
                    "description": "题型",
                    "type": "string"
                }
            }
        },
        "qa.SessionDetailResponse": {
            "type": "object",
            "properties": {
                "agent": {
                    "description": "Agent名称",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间（永久为空）",
                    "type": "string"
                },
                "hash": {
                    "description": "会话哈希标识",
                    "type": "string"
                },
                "id": {
                    "description": "Session ID",
                    "type": "string"
                },
                "online_devices": {
                    "description": "在线设备数",
                    "type": "integer"
                },
                "project_id": {
                    "description": "关联项目ID",
                    "type": "string"
                },
                "project_name": {
                    "description": "关联项目名称",
                    "type": "string"
                },
                "questions": {
                    "description": "问题列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/qa.QuestionSummaryResponse"
                    }
                },
                "status": {
                    "description": "active/expired/deleted",
                    "type": "string"
                },
                "title": {
                    "description": "会话标题",
                    "type": "string"
                },
                "type": {
                    "description": "temporary/permanent",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "qa.SessionListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "Session列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/qa.SessionResponse"
                    }
                },
                "total": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "qa.SessionResponse": {
            "type": "object",
            "properties": {
                "agent": {
                    "description": "Agent名称",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "expires_at": {
                    "description": "过期时间（永久为空）",
                    "type": "string"
                },
                "hash": {
                    "description": "会话哈希标识",
                    "type": "string"
                },
                "id": {
                    "description": "Session ID",
                    "type": "string"
                },
                "online_devices": {
                    "description": "在线设备数",
                    "type": "integer"
                },
                "project_id": {
                    "description": "关联项目ID",
                    "type": "string"
                },
                "project_name": {
                    "description": "关联项目名称",
                    "type": "string"
                },
                "status": {
                    "description": "active/expired/deleted",
                    "type": "string"
                },
                "title": {
                    "description": "会话标题",
                    "type": "string"
                },
                "type": {
                    "description": "temporary/permanent",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "qa.SupplementResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "内容",
                    "type": "string"
                },
                "content_type": {
                    "description": "markdown/html",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "补充内容ID",
                    "type": "string"
                },
                "target_id": {
                    "description": "关联ID",
                    "type": "string"
                },
                "target_type": {
                    "description": "question/option",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "qa.UpdateQaConfigRequest": {
            "type": "object",
            "properties": {
                "max_retries": {
                    "description": "qa_get_answer 最大重试次数（达到后返回STOPPED），nil不更新",
                    "type": "integer"
                },
                "poll_slice": {
                    "description": "qa_get_answer 单次阻塞上限（秒），nil不更新",
                    "type": "integer"
                },
                "runtime_domain": {
                    "description": "运行时域名，nil不更新",
                    "type": "string"
                },
                "session_ttl": {
                    "description": "Session TTL（秒），nil不更新",
                    "type": "integer"
                }
            }
        },
        "user.UserInfoResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "xModels.PageResponse-array_apikey_ApikeyItem": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apikey.ApikeyItem"
                    }
                },
                "size": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
